# Generated by Django 4.0 on 2021-12-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
