# Generated by Django 4.0 on 2022-01-09 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 9, 4, 40, 19, 317527, tzinfo=utc)),
        ),
    ]
