# Generated by Django 4.0 on 2022-01-24 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restfulapi', '0012_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='captcha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='驗證碼'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='id',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='使用者ID'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='證照名稱'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='訊息'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 9, 4, 37, 250474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='使用者ID'),
        ),
    ]
